#!/bin/sh
# Diagnostic script - writes environment info to a temp file
# This helps debug publish container issues
DIAG="/tmp/ghms-diag.txt"
echo "=== GHMS DIAGNOSTICS ===" > "$DIAG"
echo "Date: $(date)" >> "$DIAG"
echo "CWD: $(pwd)" >> "$DIAG"
echo "PATH: $PATH" >> "$DIAG"
echo "USER: $(whoami 2>/dev/null || echo unknown)" >> "$DIAG"
echo "HOSTNAME: $(hostname 2>/dev/null || echo unknown)" >> "$DIAG"
echo "OS: $(uname -a 2>/dev/null)" >> "$DIAG"
echo "Shell: $SHELL" >> "$DIAG"
echo "--- Runtimes ---" >> "$DIAG"
which node 2>/dev/null && echo "node: $(node --version 2>&1)" >> "$DIAG" || echo "node: NOT FOUND" >> "$DIAG"
which bun 2>/dev/null && echo "bun: $(bun --version 2>&1)" >> "$DIAG" || echo "bun: NOT FOUND" >> "$DIAG"
echo "--- Disk ---" >> "$DIAG"
df -h / 2>/dev/null >> "$DIAG"
echo "--- Memory ---" >> "$DIAG"
free -m 2>/dev/null >> "$DIAG" || echo "free not available" >> "$DIAG"
echo "--- Files ---" >> "$DIAG"
ls -la / 2>/dev/null | head -20 >> "$DIAG"
echo "--- LD ---" >> "$DIAG"
ldd --version 2>&1 | head -1 >> "$DIAG"
echo "=== END ===" >> "$DIAG"
echo "Diagnostics written to $DIAG"
cat "$DIAG"