#!/usr/bin/env python3
"""Fix i18n for subscriptions-page.tsx and subscription-plans-page.tsx (superuser pages)."""
import json, re

# ═══════════════════════════════════════════════════════
# 1. NEW LOCALE KEYS
# ═══════════════════════════════════════════════════════

NEW_KEYS = {
  "en": {
    # --- superSubscriptions namespace ---
    "superSubscriptions": {
      "pageTitle": "Subscriptions",
      "pageSubtitle": "Manage provider subscriptions, payments, and service access.",
      "btnRefresh": "Refresh",
      "filterAll": "All Status",
      "filterActive": "Active",
      "filterWarning": "Warning (Expiring)",
      "filterExpired": "Expired",
      "filterSuspended": "Suspended",
      "cardTotal": "Total",
      "cardActive": "Active",
      "cardWarning": "Warning",
      "cardGrace": "Grace",
      "cardSuspended": "Suspended",
      "thProvider": "Provider",
      "thOwner": "Owner",
      "thPhone": "Phone",
      "thPlan": "Plan",
      "thCycle": "Cycle",
      "thPrice": "Price",
      "thStatus": "Status",
      "thEnds": "Ends",
      "thPayments": "Payments",
      "thActions": "Actions",
      "noProviders": "No providers found.",
      "noMatchingSubs": "No {{status}}subscriptions found.",
      "badgePendingApproval": "Pending Approval — Click to verify",
      "noPlan": "No plan",
      "trial": "Trial",
      "btnHistoryTitle": "Payment history",
      "btnEditTitle": "Edit price/cycle",
      "btnMarkPaymentTitle": "Mark payment",
      "dlgEditTitle": "Edit Subscription",
      "dlgEditDesc": "Update price and billing cycle for",
      "lblPricePerCycle": "Price per Cycle (ETB)",
      "placeholderPrice": "Enter price",
      "lblBillingCycle": "Billing Cycle",
      "cycleMonthlyDays": "Monthly (30 days)",
      "cycleQuarterlyDays": "Quarterly (90 days)",
      "cycleSemiAnnualDays": "Semi-Annual (180 days)",
      "cycleYearlyDays": "Yearly (365 days)",
      "btnCancel": "Cancel",
      "btnSaveChanges": "Save Changes",
      "dlgPayTitle": "Record Payment",
      "dlgPayDesc": "Confirm payment for",
      "dlgPayExtend": "This will extend their subscription by one",
      "dlgPayCycleSuffix": "cycle.",
      "lblSelectPlan": "Select Plan (optional)",
      "placeholderSelectPlan": "Choose a plan to auto-fill",
      "noPlanManual": "No plan (manual entry)",
      "lblAmountEtb": "Amount (ETB)",
      "placeholderAmount": "Payment amount",
      "lblCycle": "Cycle",
      "lblNotes": "Notes (optional)",
      "placeholderNotes": "e.g., Cash payment received",
      "btnConfirmPayment": "Confirm Payment",
      "dlgVerifyTitle": "Verify Payment",
      "dlgVerifyDesc": "Review the submitted payment and approve or decline.",
      "noPendingPayments": "No pending payments found.",
      "paymentOf": "{{current}} of {{total}}",
      "badgePending": "Pending",
      "lblSubmitted": "Submitted",
      "lblPeriodStart": "Period Start",
      "lblPeriodEnd": "Period End",
      "lblPaymentMethod": "Payment Method: ",
      "lblReference": "Reference: ",
      "lblDeclineReason": "Decline Reason (required)",
      "lblApprovalNote": "Approval Note (optional)",
      "placeholderDeclineReason": "e.g., The reference number does not match our records. Please double-check and resubmit.",
      "placeholderApprovalNote": "e.g., Verified via bank statement",
      "declineReasonRequired": "You must provide a reason when declining a payment. The provider will receive this message.",
      "btnDecline": "Decline",
      "btnApprove": "Approve",
      "btnBack": "Back",
      "btnConfirmDecline": "Confirm Decline",
      "dlgHistoryTitle": "Payment History",
      "dlgHistoryDesc": "All payments for",
      "noPaymentsRecorded": "No payments recorded.",
      "badgePaymentOverdue": "Payment Overdue",
      "badgePendingVerification": "Pending Verification",
      "badgePaid": "Paid",
      "btnClose": "Close",
      "toastFailedLoad": "Failed to load",
      "toastFailedLoadPending": "Failed to load pending payments",
      "toastApproved": "Approved",
      "toastRejected": "Rejected",
      "toastApprovedRemaining": "{{action}} payment of {{amount}} ETB — {{remaining}} remaining",
      "toastActionForProvider": "{{action}} payment for {{provider}}",
      "toastActionFailed": "Failed to {{action}} payment",
      "toastUpdatedFor": "Updated subscription for {{provider}}",
      "toastFailedUpdate": "Failed to update",
      "toastPaymentRecorded": "Payment recorded for {{provider}}",
      "toastFailedRecord": "Failed to record payment",
      "toastFailedLoadHistory": "Failed to load payment history",
      "statusACTIVE": "ACTIVE",
      "statusWARNING": "WARNING",
      "statusEXPIRED": "EXPIRED",
      "statusSUSPENDED": "SUSPENDED",
    },
    # --- superPlans namespace ---
    "superPlans": {
      "pageTitle": "Pricing Plans",
      "pageSubtitle": "Define and manage subscription pricing plans for guest house providers.",
      "btnRefresh": "Refresh",
      "btnCreatePlan": "Create Plan",
      "noPlansTitle": "No Plans Yet",
      "noPlansDesc": "Create your first pricing plan to define subscription tiers for guest house providers.",
      "btnCreateFirstPlan": "Create First Plan",
      "badgeActive": "Active",
      "badgeInactive": "Inactive",
      "lblPrice": "Price",
      "lblProviders": "providers",
      "lblCycleSuffix": "cycle",
      "toggleActive": "Active",
      "toggleInactive": "Inactive",
      "btnEditPlanTitle": "Edit plan",
      "btnDeletePlanTitle": "Delete plan",
      "perMonth": "~{{amount}} ETB / month",
      "dlgEditTitle": "Edit Plan",
      "dlgCreateTitle": "Create New Plan",
      "dlgEditDesc": "Update the pricing details for",
      "dlgCreateDesc": "Define a new subscription pricing plan for providers.",
      "lblPlanName": "Plan Name",
      "placeholderPlanName": "e.g., Monthly, Quarterly, Premium Annual",
      "lblBillingCycle": "Billing Cycle",
      "placeholderSelectCycle": "Select cycle",
      "cycleMonthlyDays": "Monthly (30 days)",
      "cycleQuarterlyDays": "Quarterly (90 days)",
      "cycleSemiAnnualDays": "Semi-Annual (180 days)",
      "cycleYearlyDays": "Yearly (365 days)",
      "lblPriceEtb": "Price (ETB)",
      "placeholderPriceEtb": "Enter price in ETB",
      "priceCalc": "{{cycle}} · {{days}} days · ~{{perMonth}} ETB/month",
      "planInfo": "Plan Info",
      "providersOnPlan": "{{count}} provider(s) currently on this plan",
      "btnCancel": "Cancel",
      "btnSaveChanges": "Save Changes",
      "btnCreatePlanBtn": "Create Plan",
      "dlgDeleteTitle": "Delete Plan",
      "dlgDeleteHasSubs": "The plan has {{count}} provider(s) subscribed to it. It will be deactivated instead of permanently deleted.",
      "dlgDeleteNoSubs": "Are you sure you want to delete? This action cannot be undone.",
      "btnDeactivate": "Deactivate Plan",
      "btnDeletePermanently": "Delete Permanently",
      "toastFailedLoad": "Failed to load plans",
      "toastFillRequired": "Please fill in all fields",
      "toastUpdated": "Plan updated",
      "toastCreated": "Plan created",
      "toastFailedSave": "Failed to save plan",
      "toastDeactivated": "Plan deactivated",
      "toastActivated": "Plan activated",
      "toastFailedToggle": "Failed to toggle plan",
      "toastDeleted": "Plan deleted",
      "toastFailedDelete": "Failed to delete plan",
    },
  },
  "am": {
    "superSubscriptions": {
      "pageTitle": "ይዞታዎች",
      "pageSubtitle": "የአቅራቢያ ይዞታዎችን፣ ክፍያዎችን እና የአገልግሎት መዳረሻን ያስተዳድሩ።",
      "btnRefresh": "አድስ",
      "filterAll": "ሁሉም ሁኔታ",
      "filterActive": "ንቁ",
      "filterWarning": "ማስጠንቀቅ (የሚያበቃ)",
      "filterExpired": "የተወለደ",
      "filterSuspended": "የተቋረጠ",
      "cardTotal": "ጠቅላላ",
      "cardActive": "ንቁ",
      "cardWarning": "ማስጠንቀቅ",
      "cardGrace": "ጸጥታ",
      "cardSuspended": "የተቋረጠ",
      "thProvider": "አቅራቢያ",
      "thOwner": "ባለቤት",
      "thPhone": "ስልክ",
      "thPlan": "ዕቅድ",
      "thCycle": "ዑደት",
      "thPrice": "ዋጋ",
      "thStatus": "ሁኔታ",
      "thEnds": "የሚያበቃ",
      "thPayments": "ክፍያዎች",
      "thActions": "ተግባራት",
      "noProviders": "ምንም አቅራቢያዎች አልተገኙም።",
      "noMatchingSubs": "ምንም {{status}}ይዞታዎች አልተገኙም።",
      "badgePendingApproval": "ማፅዳት የሚጠብቅ — ለማረጋገጥ ይጫኑ",
      "noPlan": "ዕቅድ የለም",
      "trial": "ሙከራ",
      "btnHistoryTitle": "የክፍያ ታሪክ",
      "btnEditTitle": "ዋጋ/ዑደት አስተካክል",
      "btnMarkPaymentTitle": "ክፍድል ምልክት አድርግ",
      "dlgEditTitle": "ይዞታ አስተካክል",
      "dlgEditDesc": "ዋጋ እና የክፍያ ዑደት ያዘምኑ",
      "lblPricePerCycle": "ዋጋ በዑደት (ETB)",
      "placeholderPrice": "ዋጋ ያስገቡ",
      "lblBillingCycle": "የክፍያ ዑደት",
      "cycleMonthlyDays": "ወርሃዊ (30 ቀናት)",
      "cycleQuarterlyDays": "ሩብ ዓመታዊ (90 ቀናት)",
      "cycleSemiAnnualDays": "ግማሽ ዓመታዊ (180 ቀናት)",
      "cycleYearlyDays": "ዓመታዊ (365 ቀናት)",
      "btnCancel": "ሰርዝ",
      "btnSaveChanges": "ለውጦችን አስቀምጥ",
      "dlgPayTitle": "ክፍድል መዝገብ",
      "dlgPayDesc": "ክፍድል አረጋግጥ",
      "dlgPayExtend": "ይዞታያቸውን በአንድ",
      "dlgPayCycleSuffix": "ዑደት ያራዝ።",
      "lblSelectPlan": "ዕቅድ ይምረጡ (አስማሚ)",
      "placeholderSelectPlan": "ለራስ-ሙላ ዕቅድ ይምረጡ",
      "noPlanManual": "ዕቅድ የለም (እጅግ ማስገባት)",
      "lblAmountEtb": "መጠን (ETB)",
      "placeholderAmount": "የክፍያ መጠን",
      "lblCycle": "ዑደት",
      "lblNotes": "ማስታወሻ (አስማሚ)",
      "placeholderNotes": "ለም. የንግድ ክፍያ ተቀብሏል",
      "btnConfirmPayment": "ክፍድል አረጋግጥ",
      "dlgVerifyTitle": "ክፍድል አረጋግጥ",
      "dlgVerifyDesc": "የተላከውን ክፍድል ግምገሙ እና ይቀበሉ ወይም ይከለክሉ።",
      "noPendingPayments": "ምንም የሚጠብቅ ክፍያዎች አልተገኙም።",
      "paymentOf": "{{current}} ከ {{total}}",
      "badgePending": "የሚጠብቅ",
      "lblSubmitted": "የተላከ",
      "lblPeriodStart": "የዘመን መጀመሪያ",
      "lblPeriodEnd": "የዘመን መጨረሻ",
      "lblPaymentMethod": "የክፍድል ዘዴ: ",
      "lblReference": "ማመሳከሪያ: ",
      "lblDeclineReason": "የማከለከል ምክንያ (ይጠይቃል)",
      "lblApprovalNote": "የማጽዳት ማስታወሻ (አስማሚ)",
      "placeholderDeclineReason": "ለም. ማመሳከሪያ ቁጥሩ ከመዝገባችን ጋር አይጣጣም። እባክዎ ዳግም ያረጋግጡ እና ይላኩ።",
      "placeholderApprovalNote": "ለም. በባንክ ደረሰኝ ተረጋግጧል",
      "declineReasonRequired": "ክፍድል ሲከለክሉ ምክንያ ማስገባት ይገባዎታል። አቅራቢያው ይህን መልዕክት ይቀበላል።",
      "btnDecline": "ከለክል",
      "btnApprove": "አጽድ",
      "btnBack": "ተመለስ",
      "btnConfirmDecline": "ከለክል አረጋግጥ",
      "dlgHistoryTitle": "የክፍያ ታሪክ",
      "dlgHistoryDesc": "ለ",
      "noPaymentsRecorded": "ምንም ክፍያዎች አልተመዝገቡም።",
      "badgePaymentOverdue": "ክፍድል ጊዜው አልፏል",
      "badgePendingVerification": "ማረጋገጥ የሚጠብቅ",
      "badgePaid": "ተከፍሏል",
      "btnClose": "ዝጋ",
      "toastFailedLoad": "መጫን አልተሳካም",
      "toastFailedLoadPending": "የሚጠብቅ ክፍያዎች መጫን አልተሳካም",
      "toastApproved": "ተቀባይነት አገኘ",
      "toastRejected": "ተከለከለ",
      "toastApprovedRemaining": "{{amount}} ETB {{action}} ክፍድል — {{remaining}} ቀርቷል",
      "toastActionForProvider": "{{provider}} {{action}} ክፍድል",
      "toastActionFailed": "{{action}} ክፍድል አልተሳካም",
      "toastUpdatedFor": "{{provider}} ይዞታ ተዘምጧል",
      "toastFailedUpdate": "ማዘመን አልተሳካም",
      "toastPaymentRecorded": "{{provider}} ክፍድል ተመዝግቧል",
      "toastFailedRecord": "ክፍድል መዝገብ አልተሳካም",
      "toastFailedLoadHistory": "የክፍያ ታሪክ መጫን አልተሳካም",
      "statusACTIVE": "ንቁ",
      "statusWARNING": "ማስጠንቀቅ",
      "statusEXPIRED": "የተወለደ",
      "statusSUSPENDED": "የተቋረጠ",
    },
    "superPlans": {
      "pageTitle": "የዋጋ ዕቅዶች",
      "pageSubtitle": "ለበጎ አድራጂ አቅራቢያዎች የይዞታ ዋጋ ዕቅዶችን ይግለጹ እና ያስተዳድሩ።",
      "btnRefresh": "አድስ",
      "btnCreatePlan": "ዕቅድ ፍጠር",
      "noPlansTitle": "ገና ዕቅዶች የሉም",
      "noPlansDesc": "ለበጎ አድራጂ አቅራቢያዎች የይዞታ ደረጃዎችን ለመግለጽ የመጀመሪያ ዋጋ ዕቅድ ፍጠሩ።",
      "btnCreateFirstPlan": "የመጀመሪያ ዕቅድ ፍጠር",
      "badgeActive": "ንቁ",
      "badgeInactive": "ንቁ ያልሆነ",
      "lblPrice": "ዋጋ",
      "lblProviders": "አቅራቢያዎች",
      "lblCycleSuffix": "ዑደት",
      "toggleActive": "ንቁ",
      "toggleInactive": "ንቁ ያልሆነ",
      "btnEditPlanTitle": "ዕቅድ አስተካክል",
      "btnDeletePlanTitle": "ዕቅድ ሰርዝ",
      "perMonth": "~{{amount}} ETB / ወር",
      "dlgEditTitle": "ዕቅድ አስተካክል",
      "dlgCreateTitle": "አዲስ ዕቅድ ፍጠር",
      "dlgEditDesc": "የዋጋ ዝርዝሮችን ያዘምኑ",
      "dlgCreateDesc": "ለአቅራቢያዎች አዲስ የይዞታ ዋጋ ዕቅድ ይግለጡ።",
      "lblPlanName": "የዕቅድ ስም",
      "placeholderPlanName": "ለም. ወርሃዊ፣ ሩብ ዓመታዊ፣ ቅን ዓመታዊ",
      "lblBillingCycle": "የክፍያ ዑደት",
      "placeholderSelectCycle": "ዑደት ይምረጡ",
      "cycleMonthlyDays": "ወርሃዊ (30 ቀናት)",
      "cycleQuarterlyDays": "ሩብ ዓመታዊ (90 ቀናት)",
      "cycleSemiAnnualDays": "ግማሽ ዓመታዊ (180 ቀናት)",
      "cycleYearlyDays": "ዓመታዊ (365 ቀናት)",
      "lblPriceEtb": "ዋጋ (ETB)",
      "placeholderPriceEtb": "በETB ዋጋ ያስገቡ",
      "priceCalc": "{{cycle}} · {{days}} ቀናት · ~{{perMonth}} ETB/ወር",
      "planInfo": "የዕቅድ መረጃ",
      "providersOnPlan": "{{count}} አቅራቢያ(ዎች) በዚህ ዕቅድ ላይ ናቸው",
      "btnCancel": "ሰርዝ",
      "btnSaveChanges": "ለውጦችን አስቀምጥ",
      "btnCreatePlanBtn": "ዕቅድ ፍጠር",
      "dlgDeleteTitle": "ዕቅድ ሰርዝ",
      "dlgDeleteHasSubs": "ዕቅዱ {{count}} አቅራቢያ(ዎች) የተመዘገቡ አሉት። ለዘላቂ ማጥፋት ይልቁንና ይሰናሳል።",
      "dlgDeleteNoSubs": "ማጥፋት ይፈልጋሉ? ይህ ተግባር መልሰው ማስተካክል አይችሉም።",
      "btnDeactivate": "ዕቅድ አሰናሳ",
      "btnDeletePermanently": "ለዘላቂ ሰርዝ",
      "toastFailedLoad": "ዕቅዶችን መጫን አልተሳካም",
      "toastFillRequired": "እባክዎ ሁሉንም መስኮቶች ይሙሉ",
      "toastUpdated": "ዕቅድ ተዘምጧል",
      "toastCreated": "ዕቅድ ተፈጥሯል",
      "toastFailedSave": "ዕቅድ ማስቀመጥ አልተሳካም",
      "toastDeactivated": "ዕቅድ ተሰናሳል",
      "toastActivated": "ዕቅድ ተቀጥሯል",
      "toastFailedToggle": "ዕቅድ መቀያየር አልተሳካም",
      "toastDeleted": "ዕቅድ ተሰርዟል",
      "toastFailedDelete": "ዕቅድ መሰረዝ አልተሳካም",
    },
  },
  "om": {
    "superSubscriptions": {
      "pageTitle": "Qabiyyee",
      "pageSubtitle": "Qabiyyee hommaa fiichisaa, kabajii fi daanga dubbistoota tajaajilaa dalaguu.",
      "btnRefresh": "Haqa",
      "filterAll": "Haalli Hunda",
      "filterActive": "Haala",
      "filterWarning": "Yaaddoo (Dhufaa Jira)",
      "filterExpired": "Dhufeera",
      "filterSuspended": "Dhiibameera",
      "cardTotal": "Qabxii",
      "cardActive": "Haala",
      "cardWarning": "Yaaddoo",
      "cardGrace": "Sirrii",
      "cardSuspended": "Dhiibameera",
      "thProvider": "Fiichisaa",
      "thOwner": "Mataa Dhaabbii",
      "thPhone": "Bilbila",
      "thPlan": "Qajeelfama",
      "thCycle": "Muddee",
      "thPrice": "Gatii",
      "thStatus": "Haalli",
      "thEnds": "Xumuru",
      "thPayments": "Kabajii",
      "thActions": "Tarkaanfii",
      "noProviders": "Fiichisaawwan hin argamne.",
      "noMatchingSubs": "{{status}}qabiyyee hin argamne.",
      "badgePendingApproval": "Mirkanaa'aa Jira — Qajeelfamuu Qabadhu",
      "noPlan": "Qajeelfama hin jiru",
      "trial": "Eegumsa",
      "btnHistoryTitle": "Seenaa Kabajii",
      "btnEditTitle": "Gatii/Muddee Gulaaluu",
      "btnMarkPaymentTitle": "Kabajii Mallattoo",
      "dlgEditTitle": "Qabiyyee Gulaaluu",
      "dlgEditDesc": "Gatii fi kabajii muddee haqaaji",
      "lblPricePerCycle": "Gatii Muddee Tokko (ETB)",
      "placeholderPrice": "Gatii galchi",
      "lblBillingCycle": "Kabajii Muddee",
      "cycleMonthlyDays": "Guraandala (30 guyyaa)",
      "cycleQuarterlyDays": "Kubbaa Waggaa (90 guyyaa)",
      "cycleSemiAnnualDays": "Dhahannaa Waggaa (180 guyyaa)",
      "cycleYearlyDays": "Waggaa (365 guyyaa)",
      "btnCancel": "Dhiisi",
      "btnSaveChanges": "Jijjiiramoota Olkaa'i",
      "dlgPayTitle": "Kabajii Galmeessi",
      "dlgPayDesc": "Kabajii mirkaneessi",
      "dlgPayExtend": "Qabiyyee isaanii muddee tokkoon",
      "dlgPayCycleSuffix": "haqa'i.",
      "lblSelectPlan": "Qajeelfama Filadhu (dubbisuu danda'uu)",
      "placeholderSelectPlan": "Qajeelfama filadhu",
      "noPlanManual": "Qajeelfama hin jiru (galchi dhuunfaa)",
      "lblAmountEtb": "Baay'ina (ETB)",
      "placeholderAmount": "Kabajii baay'ina",
      "lblCycle": "Muddee",
      "lblNotes": "Yaada (dubbisuu danda'uu)",
      "placeholderNotes": "Fkn. Kabajii birr qabanneera",
      "btnConfirmPayment": "Kabajii Mirkaneessi",
      "dlgVerifyTitle": "Kabajii Mirkaneessi",
      "dlgVerifyDesc": "Kabajii ergame mirkaneessi fi jaallachi ykn hiriyya.",
      "noPendingPayments": "Kabajii eeggachuu hin jiru.",
      "paymentOf": "{{current}} kan {{total}}",
      "badgePending": "Eeggachuu Jira",
      "lblSubmitted": "Ergameera",
      "lblPeriodStart": "Deebii Jalqaba",
      "lblPeriodEnd": "Deebii Xumuru",
      "lblPaymentMethod": "Tarkaanfii Kabajii: ",
      "lblReference": "Rukuttaa: ",
      "lblDeclineReason": "Sababaa Hiriya (barbaachisaa)",
      "lblApprovalNote": "Yaada Mirkanaa (dubbisuu danda'uu)",
      "placeholderDeclineReason": "Fkn. Lakkoofsa rukuttaa xiyyeeffannoo keenya waliin wal hin simatan. Dabalataan ilaali fi irra deebi'i.",
      "placeholderApprovalNote": "Fkn. Kuusaa bankii irraa mirkaneefameera",
      "declineReasonRequired": "Kabajii hiriyaatteetti sababaa kennuu qabda. Fiicha isaanii ergaa kana argatu.",
      "btnDecline": "Hiriya",
      "btnApprove": "Jaalladhu",
      "btnBack": "Deebi'i",
      "btnConfirmDecline": "Hiriya Mirkaneessi",
      "dlgHistoryTitle": "Seenaa Kabajii",
      "dlgHistoryDesc": "Kan",
      "noPaymentsRecorded": "Kabajii galmeeffamne hin jiru.",
      "badgePaymentOverdue": "Kabajii Yeroo Dhufe",
      "badgePendingVerification": "Mirkanaa'uu Eeggachuu Jira",
      "badgePaid": "Kabameera",
      "btnClose": "Cufi",
      "toastFailedLoad": "Fayyadamaan hin argamne",
      "toastFailedLoadPending": "Kabajii eeggachuu argachuu hin danda'ne",
      "toastApproved": "Mirkanaa'aa",
      "toastRejected": "Hir'atameera",
      "toastApprovedRemaining": "{{amount}} ETB {{action}} kabajii — {{remaining}} hafe",
      "toastActionForProvider": "{{provider}} {{action}} kabajii",
      "toastActionFailed": "{{action}} kabajii hin danda'ne",
      "toastUpdatedFor": "{{provider}} qabiyyee haqaawameera",
      "toastFailedUpdate": "Haqaachuu hin danda'ne",
      "toastPaymentRecorded": "{{provider}} kabajii galmeeffameera",
      "toastFailedRecord": "Kabajii galmeessuu hin danda'ne",
      "toastFailedLoadHistory": "Seenaa kabajii fayyadamaan hin argamne",
      "statusACTIVE": "Haala",
      "statusWARNING": "Yaaddoo",
      "statusEXPIRED": "Dhufeera",
      "statusSUSPENDED": "Dhiibameera",
    },
    "superPlans": {
      "pageTitle": "Qajeelfamoota Gatii",
      "pageSubtitle": "Qajeelfamoota gatii qabiyyee kan fiichisaa buna qabeeyyii ibsi fi dalagaa.",
      "btnRefresh": "Haqa",
      "btnCreatePlan": "Qajeelfama Uumi",
      "noPlansTitle": "Qajeelfamoota Hin Jiru",
      "noPlansDesc": "Qajeelfama gatii qabiyyee kan dhaabbiiwwan buna qabeeyyii haaraadhaan uumi.",
      "btnCreateFirstPlan": "Qajeelfama Jalqabaa Uumi",
      "badgeActive": "Haala",
      "badgeInactive": "Haala Hin Taane",
      "lblPrice": "Gatii",
      "lblProviders": "Fiichisaawwan",
      "lblCycleSuffix": "muddee",
      "toggleActive": "Haala",
      "toggleInactive": "Haala Hin Taane",
      "btnEditPlanTitle": "Qajeelfama gulaaluu",
      "btnDeletePlanTitle": "Qajeelfama haquu",
      "perMonth": "~{{amount}} ETB / ji'a",
      "dlgEditTitle": "Qajeelfama Gulaaluu",
      "dlgCreateTitle": "Qajeelfama Haaraa Uumi",
      "dlgEditDesc": "Odeeffannoo gatii haqaajuu",
      "dlgCreateDesc": "Qajeelfama gatii qabiyyee haaraa fiichisaawwanif ibsi.",
      "lblPlanName": "Maqaa Qajeelfamaa",
      "placeholderPlanName": "Fkn. Guraandala, Kubbaa Waggaa, Waggaa Guutuu",
      "lblBillingCycle": "Kabajii Muddee",
      "placeholderSelectCycle": "Muddee filadhu",
      "cycleMonthlyDays": "Guraandala (30 guyyaa)",
      "cycleQuarterlyDays": "Kubbaa Waggaa (90 guyyaa)",
      "cycleSemiAnnualDays": "Dhahannaa Waggaa (180 guyyaa)",
      "cycleYearlyDays": "Waggaa (365 guyyaa)",
      "lblPriceEtb": "Gatii (ETB)",
      "placeholderPriceEtb": "Gatii ETB keessatti galchi",
      "priceCalc": "{{cycle}} · {{days}} guyyaa · ~{{perMonth}} ETB/ji'a",
      "planInfo": "Odeeffannoo Qajeelfamaa",
      "providersOnPlan": "{{count}} fiichisaa(qabeeyyii) qajeelfama kana irratti jira",
      "btnCancel": "Dhiisi",
      "btnSaveChanges": "Jijjiiramoota Olkaa'i",
      "btnCreatePlanBtn": "Qajeelfama Uumi",
      "dlgDeleteTitle": "Qajeelfama Haquu",
      "dlgDeleteHasSubs": "Qajeelfama kana {{count}} fiichisaa(qabeeyyii) galmeeffaniiru. Yeroo dhumaatii haa fixuu,",
      "dlgDeleteNoSubs": "Haquu barbaaddaa? Tarkaanfiin kun deebi'uu hin danda'u.",
      "btnDeactivate": "Qajeelfama Fixuu",
      "btnDeletePermanently": "Yeroo Dhumaatii Haquu",
      "toastFailedLoad": "Qajeelfamoota fayyadamaan hin argamne",
      "toastFillRequired": "Meeshaa hunda bu'uurradhu",
      "toastUpdated": "Qajeelfama haqaawameera",
      "toastCreated": "Qajeelfama uumameera",
      "toastFailedSave": "Qajeelfama olkaa'uu hin danda'ne",
      "toastDeactivated": "Qajeelfama fixameera",
      "toastActivated": "Qajeelfama akeekkachiifameera",
      "toastFailedToggle": "Qajeelfama jijjiiruu hin danda'ne",
      "toastDeleted": "Qajeelfama haquameera",
      "toastFailedDelete": "Qajeelfama haquu hin danda'ne",
    },
  },
}

LOCALE_FILES = {
    "en": "src/i18n/locales/en.json",
    "am": "src/i18n/locales/am.json",
    "om": "src/i18n/locales/om.json",
}

for lang, path in LOCALE_FILES.items():
    with open(path, "r") as f:
        data = json.load(f)
    
    for ns, keys in NEW_KEYS[lang].items():
        if ns not in data:
            data[ns] = {}
        added = []
        for key, value in keys.items():
            if key not in data[ns]:
                data[ns][key] = value
                added.append(key)
        print(f"{lang}/{ns}: Added {len(added)} keys")
    
    with open(path, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("\nAll locale keys added!")
